# site settings
title: Restaurant DO
subtitle: 
description: Chinesische, Thailändische und Vietnamesische Küche
baseurl: "/restaurant" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/restaurantdo
googleplus_url: https://goo.gl/maps/zUkFzoKo2fp
instagram_url: #https://instagram.com
tripadvisor_url: https://www.tripadvisor.de/Restaurant_Review-g187310-d7909779-Reviews-China_Thai_Viet_Restaurant_DO-Nuremberg_Middle_Franconia_Franconia_Bavaria.html

# build settings
markdown: kramdown

sass:
  style: compressed
